# Generated by Django 5.1 on 2024-09-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_menuitem_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('colddrinks', 'Cold-Drinks'), ('hotdrinks', 'Hot-Drinks')], default='veg', max_length=20),
        ),
    ]
