# Generated by Django 5.1 on 2024-09-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
