# Generated by Django 5.1 on 2024-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_profile_country_profile_location_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default_profile.png', upload_to='images/'),
        ),
    ]
