# Generated by Django 5.1 on 2024-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rfid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
