# Generated by Django 5.1 on 2024-10-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_profile_profile_photo_alter_profile_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_applied_for_rfid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
